name: rexpay
description: A new Flutter plugin project.
version: 0.0.5
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^0.13.5
  intl: ^0.17.0
  meta: ^1.8.0
  async: ^2.9.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  # dart_pg: ^1.2.0
  openpgp: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  matcher: ^0.12.12
  mockito: ^5.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  
  plugin:
    platforms:
      android:
        package: com.rexpay.rexpay
        pluginClass: RexpayPlugin
      ios:
        pluginClass: RexpayPlugin

  assets:
    - assets/images/